### ISSUE TITLE
Horizontal Server List issue

### ISSUE THREAD

**Issue by TSedlar** [Gibbu/BetterDiscord-Themes#48]
The servers are being put to the top, but it's changed from being listed horizontally to vertically:

![](https://i.imgur.com/zLEKXkD.gif)

**Comment by Gibbu** [comment]
It's a new update for PTB/Canary. If you can I recommend switching to stable. If not just use this css
```css
[aria-label="Servers"],
.wrapper-21YSNc [role="group"] {
  display: flex;
}
```
