### ISSUE TITLE
[Bug] (Slate) Font size settings overriden

### ISSUE THREAD

**Issue by KaKi87** [Gibbu/BetterDiscord-Themes#52]
Using the Slate theme, user-defined font size set in Discord settings is overriden.

This should be considered as a major issue.

Thanks

**Comment by Gibbu** [comment]
Slate does have some font size variables.
```css
:root {
  --font-size-xsm: calc(var(--font-size) - 3px);
  --font-size-sm: calc(var(--font-size) - 1px);
  --font-size: 12px;
  --font-size-lg: calc(var(--font-size) + 2px);
  --font-size-xl: calc(var(--font-size) + 4px);
  --font-size-xxl: calc(var(--font-size) + 10px);
}
```
But none of them are tied directly to the chat. So changing them will affect other areas.
