### ISSUE TITLE
Is there a way I can make the user profile game section always stay open?

### ISSUE THREAD

**Issue by Toydotgame** [Gibbu/BetterDiscord-Themes#76]
Hi, the title basically sums up what I want. I don't like having to hover my mouse over the line that says `PLAYING A GAME`, and I would like to find out if I can toggle this to make the game section (in the user profile view) always open; or just what part of the code does this (so that I can make a modified copy without this part)?

**Comment by Gibbu** [comment]
```css
#app-mount .modal-3c3bKg .root-SR8cQa .activityProfile-2bJRaP .body-ZAhrcj {
  max-height: unset !important;
}
```
Paste that into your `MinimalCord.theme.css` file
